/**
 * PPRM File Format Parser
 * Converts between PPRM format (VarName[Index]=Value) and JSON arrays
 */

/**
 * Parse PPRM content to JSON structure
 * @param {string} pprmContent - Raw PPRM file content
 * @returns {Object} - Parsed data as { variables: { varName: [values] } }
 */
export function parsePprmToJson(pprmContent) {
  const variables = {};
  const lines = pprmContent.split('\n');
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    
    // Skip empty lines and comments
    if (!trimmedLine || trimmedLine.startsWith('#') || trimmedLine.startsWith('//')) {
      continue;
    }
    
    // Parse line format: VarName[Index]=Value or VarName=Value
    const arrayMatch = trimmedLine.match(/^([a-zA-Z_][a-zA-Z0-9_.]*)\[(\d+)\]=(.*)$/);
    const scalarMatch = trimmedLine.match(/^([a-zA-Z_][a-zA-Z0-9_.]*)\s*=\s*(.*)$/);

    if (arrayMatch) {
      const [, varName, index, value] = arrayMatch;
      const indexNum = parseInt(index, 10);

      // Initialize array if it doesn't exist
      if (!variables[varName]) {
        variables[varName] = [];
      }

      // Extend array if necessary
      while (variables[varName].length <= indexNum) {
        variables[varName].push('');
      }

      // Parse value - try to detect numbers, booleans, etc.
      let parsedValue = parseValue(value);

      variables[varName][indexNum] = parsedValue;
    } else if (scalarMatch) {
      const [, varName, value] = scalarMatch;

      // For scalar values, create an array with single element at index 1 (1-based indexing)
      if (!variables[varName]) {
        variables[varName] = [];
      }

      variables[varName][1] = parseValue(value);
    }
  }

  // Helper function to parse values
  function parseValue(value) {
    // Remove quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      return value.slice(1, -1);
    } else {
      // Try to parse as number
      const numValue = parseFloat(value);
      if (!isNaN(numValue) && isFinite(numValue)) {
        return numValue;
      } else if (value.toLowerCase() === 'true') {
        return true;
      } else if (value.toLowerCase() === 'false') {
        return false;
      }
      return value;
    }
  }
  
  return { variables };
}

/**
 * Convert JSON structure back to PPRM format
 * @param {Object} jsonData - Data structure { variables: { varName: [values] } }
 * @returns {string} - PPRM formatted content
 */
export function jsonToPprm(jsonData) {
  const lines = [];
  
  // Add header comment
  lines.push('# PPRM File - Generated by Configuration Manager');
  lines.push(`# Generated on: ${new Date().toISOString()}`);
  lines.push('');
  
  if (jsonData.variables) {
    // Sort variable names for consistent output
    const sortedVarNames = Object.keys(jsonData.variables).sort();
    
    for (const varName of sortedVarNames) {
      const values = jsonData.variables[varName];
      
      if (Array.isArray(values)) {
        lines.push(`# Variable: ${varName}`);

        let hasValues = false;
        for (let i = 0; i < values.length; i++) {
          const value = values[i];

          // Skip empty, undefined, or null values
          if (value === undefined || value === null || value === '') {
            continue;
          }

          let formattedValue;
          if (typeof value === 'string') {
            // Quote strings that contain spaces or special characters
            if (value.includes(' ') || value.includes('=') || value.includes('[') || value.includes(']')) {
              formattedValue = `"${value}"`;
            } else {
              formattedValue = value;
            }
          } else {
            formattedValue = String(value);
          }

          // Handle scalar case (single value at index 1 without brackets)
          if (i === 1 && values.length === 2 && values[0] === undefined) {
            lines.push(`${varName}=${formattedValue}`);
          } else {
            lines.push(`${varName}[${i}]=${formattedValue}`);
          }
          hasValues = true;
        }

        // Only add empty line if we actually wrote some values
        if (hasValues) {
          lines.push(''); // Empty line between variables
        }
      }
    }
  }
  
  return lines.join('\n');
}

/**
 * Validate PPRM content format
 * @param {string} pprmContent - Raw PPRM content to validate
 * @returns {Object} - { isValid: boolean, errors: string[] }
 */
export function validatePprmFormat(pprmContent) {
  const errors = [];
  const lines = pprmContent.split('\n');
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    const lineNumber = i + 1;
    
    // Skip empty lines and comments
    if (!line || line.startsWith('#') || line.startsWith('//')) {
      continue;
    }
    
    // Check if line matches expected format (array or scalar)
    const isArrayFormat = line.match(/^[a-zA-Z_][a-zA-Z0-9_.]*\[\d+\]=.*$/);
    const isScalarFormat = line.match(/^[a-zA-Z_][a-zA-Z0-9_.]*\s*=\s*.*$/);

    if (!isArrayFormat && !isScalarFormat) {
      errors.push(`Line ${lineNumber}: Invalid format. Expected "VarName[Index]=Value" or "VarName=Value", got: "${line}"`);
    }
  }
  
  return {
    isValid: errors.length === 0,
    errors
  };
}

/**
 * Get PPRM file statistics
 * @param {Object} jsonData - Parsed PPRM data
 * @returns {Object} - Statistics about the PPRM file
 */
export function getPprmStats(jsonData) {
  const stats = {
    variableCount: 0,
    totalValues: 0,
    variables: {}
  };
  
  if (jsonData.variables) {
    stats.variableCount = Object.keys(jsonData.variables).length;
    
    for (const [varName, values] of Object.entries(jsonData.variables)) {
      // Count only non-undefined values excluding index 0
      const validValues = Array.isArray(values) ?
        values.filter((v, i) => i > 0 && v !== undefined && v !== null && v !== '') : [];
      const valueCount = validValues.length;
      stats.totalValues += valueCount;
      stats.variables[varName] = {
        valueCount,
        dataTypes: validValues.length > 0 ?
          [...new Set(validValues.map(v => typeof v))] : []
      };
    }
  }
  
  return stats;
}
